### ISSUE TITLE
Hi, Could add some instruction on how to use this library?

### ISSUE THREAD

**Issue by incomingflyingbrick** [PyAV-Org/pyav-ffmpeg#62]
Hi there , I am trying to install pyav an arm device(aarch64 ubuntu). But I am not sure how to install this library first. could provide a instruction page on how to install this library.  Many thanks !

**Comment by incomingflyingbrick** [comment]
Hi , I used ffmpeg excutable in the bin folder to build PyAv from source, because I can't install it using pip. I am using a Nvidia jetson device. 
when I am build PyAv, it shows the following error:

**pkg-config returned flags we don't understand: -pthread -pthread -pthread
Building PyAV against static FFmpeg libraries is not supported.**

Could you tell me a correct way to build PyAv on arm device, thank you

**Comment by jlaine** [comment]
This repository exists only to facilitate building the binary wheels of PyAV, it is not expected to be used directly by users.

To build PyAV from source, you need a *dynamically linked* version of the FFmpeg libraries. The error you pasted indicates you are using a static build of FFmpeg.
