### ISSUE TITLE
Windows arm64 ffmpeg and pyav wheel?

### ISSUE THREAD

**Issue by laggykiller** [PyAV-Org/pyav-ffmpeg#86]
I am trying to build ffmpeg and ultimately pyav wheel for Windows arm64 with github ci. Here are some thoughts:

- In order to build Windows arm64 ffmpeg on github action, we have to cross compile from MINGW64 with `mingw-w64-x86_64-toolchain` installed and compile flags like `--build=x86_64-w64-mingw32 --host=aarch64-w64-mingw32` (See https://github.com/laggykiller/pyav-ffmpeg). However, if I am not mistaken, the cross-toolchain is currently not working and fail to cross compile ffmpeg's dependencies from my testing? (Note the red box with legend of 'TODO' for software: https://github.com/Windows-on-ARM-Experiments/msys2-woarm64-build?tab=readme-ov-file#minggw-toolchain-ci) Edit: The team seems to be working on cross-compiling ffmpeg itself in this repo: https://github.com/Windows-on-ARM-Experiments/mingw-woarm64-build
  - I tried to compile `xz` with `--build=x86_64-w64-mingw32 --host=aarch64-w64-mingw32 --target=aarch64-w64-mingw32` but `file /c/cibw/vendor/bin/liblzma-5.dll` gives `/c/cibw/vendor/bin/liblzma-5.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows, 21 sections` meaning that the compilation result is not aarch64
  - Compiling `gmp` gives the error [1] below. I thought using latest gmp may solve the problem (https://gmplib.org/gmp6.3) but that still fail with other error [2].

[1]:
```
...
 Error: operand size mismatch for `mov'
tmp-hamdist.s:189: Error: no such instruction: `bl Llt8k'
tmp-hamdist.s:190: Error: too many memory references for `add'
tmp-hamdist.s:191: Error: operand size mismatch for `mov'
make[2]: *** [Makefile:768: rsh1add_n.lo] Error 1
make[2]: *** [Makefile:768: rsh1sub_n.lo] Error 1
make[2]: *** [Makefile:768: hamdist.lo] Error 1
make[2]: Leaving directory '/d/Downloads/pyav-ffmpeg/build/gmp/mpn'
make[1]: *** [Makefile:997: all-recursive] Error 1
make[1]: Leaving directory '/d/Downloads/pyav-ffmpeg/build/gmp'
make: *** [Makefile:787: all] Error 2
```
[2]:
```
...
tmp-divrem_1.s:219: Error: no such instruction: `cbnz x24,Lftop'
tmp-divrem_1.s:221: Error: no such instruction: `lsr x0,x11,x23'
tmp-divrem_1.s:222: Error: no such instruction: `ldp x19,x20,[sp,'
tmp-divrem_1.s:223: Error: no such instruction: `ldp x21,x22,[sp,'
tmp-divrem_1.s:224: Error: no such instruction: `ldp x23,x24,[sp,'
tmp-divrem_1.s:225: Error: no such instruction: `ldp x29,x30,[sp],'
tmp-divrem_1.s:229: Error: no such instruction: `cbz x1,Lzend'
tmp-divrem_1.s:230: Error: expecting operand after ','; got nothing
tmp-divrem_1.s:231: Error: expecting operand after ','; got nothing
tmp-divrem_1.s:232: Error: no such instruction: `cbnz x1,Lztop'
tmp-divrem_1.s:233: Error: expecting operand after ','; got nothing
make[2]: *** [Makefile:768: divrem_1.lo] Error 1
make[2]: Leaving directory '/d/Downloads/pyav-ffmpeg/build/gmp/mpn'
make[1]: *** [Makefile:998: all-recursive] Error 1
make[1]: Leaving directory '/d/Downloads/pyav-ffmpeg/build/gmp'
make: *** [Makefile:788: all] Error 2
```
- Alternatively, we can run self-hosted Windows arm64 runner and natively compile with CLANGARM64 (Which is how msys2 build CLANGARM64 packages: https://github.com/msys2/MINGW-packages/blob/7c72e4a5785cd96aef2007c36100bd5ed1a383d8/.github/workflows/main.yml#L23C72-L23C72). However, someone has to host the arm64 runner (I do have a M1 macmini that can run windows arm64 virtual machine that I am willing to use it as self-hosted runner for building wheel).
- We may also just use `mingw-w64-clang-aarch64-ffmpeg` (https://packages.msys2.org/package/mingw-w64-clang-aarch64-ffmpeg?repo=clangarm64) from msys2 repo. However, I am not sure if this is possible and permitted?
- Cross compiling from x86_64 to arm64 on Windows with msvc should be possible, but this involves a lot of rewriting in this repo.

Any thoughts? Is cross-compiling on MINGW64 really not possible currently?

**Comment by laggykiller** [comment]
Some progress:

I have added [woarm64 repo](https://github.com/Windows-on-ARM-Experiments/msys2-woarm64-build?tab=readme-ov-file#packages-repository-usage) to `/etc/pacman.conf` (You can see from the [github workflow](https://github.com/laggykiller/pyav-ffmpeg/blob/1e2ce8089cd57ad56201266e551ba3c3be5a9212/.github/workflows/build-ffmpeg.yml#L50))

Currently compilation is success until `xml2`, throwing linking errors that look like this:

```
/opt/lib/gcc/aarch64-w64-mingw32/14.0.0/../../../../aarch64-w64-mingw32/bin/ld: /d/Downloads/pyav-ffmpeg/build/xml2/xmlcatalog.c:445: undefined reference to `__imp_xmlNewCatalog'
```

**Comment by jlaine** [comment]
One place to look for inspiration is often the msys package recipes, or vcpkg. If there is a Windows / arm64 specific patch needed they usually have it.

**Comment by jlaine** [comment]
Hm I'm not convinced cross compiling from Linux is going to work, because the final library needs to be linkable from msvc, not mingw..

**Comment by laggykiller** [comment]
> cross compiling from Linux

Actually I am cross compiling from mingw64 on Windows x86_64

---

Some more progress:

For now, I would just install all dependencies of ffmpeg and then compile ffmpeg (See this [fork](https://github.com/laggykiller/pyav-ffmpeg/tree/woarm64-precompiled-deps) and the [github workflow file](https://github.com/laggykiller/pyav-ffmpeg/blob/4a1be9b1db83c35a4da79eb4ecdc0b1714712f69/.github/workflows/build-ffmpeg.yml#L74))

The build is [successful](https://github.com/laggykiller/pyav-ffmpeg/actions/runs/7687653890/job/20947933252). On my Windows arm64 system, running `ffmpeg.exe` shows info successfully, but it crashes when I try to convert a mp4 file. Event Viewer shows that `avcodec-60.dll` causes the crash:

```
Faulting application name: ffmpeg.exe, version: 0.0.0.0, time stamp: 0x65b672d8
Faulting module name: avcodec-60.dll, version: 60.31.102.0, time stamp: 0x65b672de
Exception code: 0xc0000005
Fault offset: 0x0000000000475a2c
Faulting process id: 0x0x9A4
Faulting application start time: 0x0x1DA520ED41DD49D
Faulting application path: C:\Users\laggykiller\Desktop\ffmpeg\bin\ffmpeg.exe
Faulting module path: C:\Users\laggykiller\Desktop\ffmpeg\bin\avcodec-60.dll
Report Id: 75b74fa0-f805-464e-a13b-4097e21fe384
Faulting package full name: 
Faulting package-relative application ID: 
```

I tried to compile with and without applying [this patch from mingw packaging](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-ffmpeg/0009-wrong-null-type.patch), both leading to this crash.

You may try out by downloading from artifact of the github action.

This crash needs to be investigated, then we can gradually reduce installing ffmpeg dependencies from mingw repo until we can compile from scratch.

**Comment by laggykiller** [comment]
Seems like using vcpkg is much less pain: https://github.com/laggykiller/pyav-ffmpeg/tree/vcpkg-winarm64

I have experimented with building windows arm64 av wheel on my machine with success.

I will change to use manifest mode for vcpkg such that version of ffmpeg and it's dependents could be specified.

@jlaine would you approve building ffmpeg for Windows arm64 using vcpkg instead of msys2?

**Comment by jlaine** [comment]
@laggykiller I'm sorry but no we are not going back to pulling in third-party binaries for Windows. That was what we used to have and it's a nightmare:

- We have no control over when those binaries get updated. This means for instance are hands are tied when we decide to move to the next version of FFmpeg.. or not.
- We lose feature parity between the platforms, which means tickets when users discover that feature X works on platform A and not platform B.

**Comment by laggykiller** [comment]
Actually vcpkg can be forced to build from source, and version can be specified by `vcpkg.json`

But yes, I do agree that it is a pain to maintain building with vcpkg beside the normal way

I will create my own fork and provide unofficial wheels for Windows arm64 then

**Comment by laggykiller** [comment]
In case anyone wants Windows arm64 and x86 wheels, I have built them: https://github.com/laggykiller/PyAV/releases

arm64 wheels tested to pass all unit tests on my Windows arm64 machine.
